# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x0cstreamServer\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\rSignalRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0bSignalReply\x12\x0e\n\x06signal\x18\x01 \x01(\x05\x32\xe1\x01\n\x08Streamer\x12@\n\x08SayHello\x12\x1a.streamServer.HelloRequest\x1a\x18.streamServer.HelloReply\x12I\n\x0fParrotSaysHello\x12\x1a.streamServer.HelloRequest\x1a\x18.streamServer.HelloReply0\x01\x12H\n\x0cSignalStream\x12\x1b.streamServer.SignalRequest\x1a\x19.streamServer.SignalReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=30
  _globals['_HELLOREQUEST']._serialized_end=76
  _globals['_HELLOREPLY']._serialized_start=78
  _globals['_HELLOREPLY']._serialized_end=107
  _globals['_SIGNALREQUEST']._serialized_start=109
  _globals['_SIGNALREQUEST']._serialized_end=138
  _globals['_SIGNALREPLY']._serialized_start=140
  _globals['_SIGNALREPLY']._serialized_end=169
  _globals['_STREAMER']._serialized_start=172
  _globals['_STREAMER']._serialized_end=397
# @@protoc_insertion_point(module_scope)
